### ISSUE TITLE
Better handling of invalid tokens

### ISSUE THREAD

**Issue by volrath** [lambdaisland/parseclj#15]
Currenty, when there's an invalid token, the lexer returns: `(concat ":(" (char-to-string char))`, and keeps the cursor at the same position where it was before.  This behavior mixed with the fact that `parseclj-parse` loops calling `parseclj-lex-next` until it reaches `:eof`, makes up for infinite loop freezing when there are invalid tokens in the text to parse.

I'm opening this issue since I'm not entirely sure what was the decision behind not having the lexer raise on invalid tokens.  Would it be better to raise in the parser?

**Comment by plexus** [comment]
This code is placeholder stuff that was always intended to be replaced. In other cases where the lexer encounters an error it returns a `:lex-error` token, I think in this case it should do the same, while also moving `point` ahead. A consumer can then decide if they want to abort at the first error, or if they want to continue calling `parseclj-lex-next` to get a "best effort" parse tree.
